# Generated by Django 5.1.2 on 2024-11-09 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sostenibilidad_Empresarial', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analisis',
            name='datos',
            field=models.JSONField(default=dict),
        ),
    ]
